development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: picolove_dev
  pool: 5
  username: root
  password: 
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: RailsApplication1_test
  pool: 5
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: RailsApplication1_production
  pool: 5
  username: root
  password:
  host: localhost

